import React from "react";
import { Link } from "react-router-dom";
import { Sparkles, Video } from "lucide-react";

function Landing() {
  return (
    <div className="w-full max-w-6xl mx-auto px-6 py-12 text-white">
      <h1 className="text-5xl font-extrabold mb-6 tracking-wide">
        Droxion
      </h1>

      <div className="flex flex-wrap gap-4 mb-10">
        <Link to="/generator" className="bg-green-600 hover:bg-green-700 px-5 py-2 rounded-lg text-white font-semibold shadow">
          Generator
        </Link>
        <Link to="/plans" className="bg-blue-600 hover:bg-blue-700 px-5 py-2 rounded-lg text-white font-semibold shadow">
          Pricing
        </Link>
        <Link to="/login" className="bg-gray-700 hover:bg-gray-800 px-5 py-2 rounded-lg text-white font-semibold shadow">
          Login
        </Link>
      </div>

      <h2 className="text-3xl font-bold mb-3">Create Stunning AI Reels in Seconds</h2>
      <p className="text-lg text-gray-300 mb-6 max-w-xl">
        Script. Voice. Music. Captions. Everything done automatically by AI.
      </p>

      <Link to="/generator" className="inline-flex items-center gap-2 bg-pink-600 hover:bg-pink-700 px-6 py-2 rounded-lg text-white font-medium mb-12 shadow">
        <Sparkles size={18} /> Try It Free Now
      </Link>

      <h3 className="text-2xl font-semibold flex items-center gap-2 mb-2">
        <Video size={20} /> AI Reel Demo
      </h3>
      <p className="text-gray-400 mb-4">Watch a real video generated by Droxion in just 30 seconds.</p>

      <video controls className="w-full max-w-2xl rounded-lg border border-gray-700 shadow-lg">
        <source src="/sample-reel.mp4" type="video/mp4" />
        Your browser does not support the video tag.
      </video>
    </div>
  );
}

export default Landing;
